version: "3.8"
services:
  yatla.server:
    build:
      context: ./src/server/Yatla.Server
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localcert.pfx
      - ASPNETCORE_ENVIRONMENT=Development
      - YATLA_AllowedHosts=*
      - YATLA_JsonDataStore__File=/store/dataStore.json
    ports:
      - "8001:443"
    volumes:
      - yatla_data:/store
      - ~/.aspnet/https:/https:ro

  yatla.ui:
    build:
      context: ./src/ui/
      dockerfile: Dockerfile
    environment:
      - API_BASE_URL=https://yatla.server:443
      - LIST_REFRESH_RATE=10000
    ports:
      - "8888:8888"
  
volumes:
  yatla_data: